### ISSUE TITLE
Some document mark up tags in wrong places

### ISSUE THREAD

**Issue by benwbrum** [CivilWarGovernorsOfKentucky/Mashbill#104]
Compare https://github.com/CivilWarGovernorsOfKentucky/TestDocuments/commits/master/document_xml/KYR-0001-017-0031.xml with the original.

**Comment by JeffDycus** [comment]
If I remember the call correctly, you were going to look into whether the changes Dazhi made to the stylesheet was having an effect.  I don't think it is.  As of now, the new stylesheet has only been implemented on the Omeka test site, not the live site.
