### ISSUE TITLE
"load XML" in context of the first line of annotated text

### ISSUE THREAD

**Issue by haywoodsarahe** [CivilWarGovernorsOfKentucky/Mashbill#136]
![load xml mashbill](https://user-images.githubusercontent.com/46460506/96044577-a2619f00-0e3e-11eb-9a71-86be115f7e44.PNG)
KYR-0001-004-0369
"Load XML" appears in the context for "Jos. E Mulkey," which is also the first line of the document. When the document was completed, Mashbill did not apply tags to this text. Is this coincidental? We also wonder if it this happens because it's a persName and not a placeName, which is often the first line in documents.

**Comment by benwbrum** [comment]
Working hypothesis from today's meeting: The text `load XML` appears before CeTEIcean loads the TEI to be displayed, so it may be present in the DOM on the page.  This means that our prefix selector includes it (and possibly other DOM elements) when text is selected at the beginning of the document.  However, that text is not present in the actual TEI document, so Mashbill's attempt to find the correct context fails.

**Comment by saracarl** [comment]
KYR-0001-004-0369 is failing because there is a "." after "Jos" that is being compared to just "Jos" without a period.  This is a problem, but not related to load XML.  Opening new issue on it.
