### ISSUE TITLE
Unknown date?

### ISSUE THREAD

**Issue by PatrickALewis** [CivilWarGovernorsOfKentucky/Mashbill#16]
Is there a difference between blank date and unknown? Is that implied by an empty field?

**Comment by benwbrum** [comment]
Is there a difference between "we've researched this and couldn't find a date" and "we haven't even looked at this yet"?  If so, maybe we should allow `"unknown"` as a value to express the former and let `blank` represent the latter.

**Comment by PatrickALewis** [comment]
Exactly. That's a far more eloquent expression of what I meant
