### ISSUE TITLE
Annotations when Omeka doc changes

### ISSUE THREAD

**Issue by PatrickALewis** [CivilWarGovernorsOfKentucky/Mashbill#18]
KYR-0362-001-0001 T. W. Owings missing. Or KYR-0001-004-0134 Night

**Comment by saracarl** [comment]
the concern is when the Omeka rendering changes for a document that already had annotations -- what happens to the annotations?  Do they become unmoored because the anchor target selector no longer refers to a valid region of the DOM.

Use the above example to test this (if possible)

**Comment by saracarl** [comment]
first case was just missing a name, the 2nd case was a missing column in the Omeka rendere.

**Comment by saracarl** [comment]
@PatrickALewis please make sure that both of these docs "pre" fixing have annotations on them that we can test with.

**Comment by PatrickALewis** [comment]
They do.

I looked into http://discovery.civilwargovernors.org/document/KYR-0362-001-0001 more. The Omeka style sheet issue went deeper than we thought. Because it can't figure out how to render the material between multi-columns (committee names and T. W. Owings), it just stripped those out of the HTML entirely. 

Could page notes be a temporary solution to hang an annotation off of text that isn't present?

**Comment by JeffDycus** [comment]
I've will be continuing to work with the stylesheet to get these documents to render correctly in Omeka, but this also leads to a larger question about documents changing in Omeka.  I'm going to create a new issue for that discussion.

**Comment by saracarl** [comment]
for testing can also work with a "private" document in Omeka and change it/update it to test how easy it is to identify an annotation if the document changed after it was annotated.

**Comment by benwbrum** [comment]
I think this may have #87 as a side effect, since the annotation target selector contains paragraph tags which are no longer present in Omeka.  We can handle this in Mashbill through error handling, once we understand what changed.
