### ISSUE TITLE
evolving documents in CWG

### ISSUE THREAD

**Issue by JeffDycus** [CivilWarGovernorsOfKentucky/Mashbill#27]

**Comment by JeffDycus** [comment]
We've spent some time this week talking about the various states documents are in as they move through the CWG editorial process and identified some disconnects that we need to iron out.  Someone please correct my errors in describing the editorial process or how Github functions.

At present, documents go through the initial stages of the of the editorial process (markup, transcription, single-proofing, etc?) in DocTracker.  XML is exported from DocTracker and imported into Omeka and reside in the XML folder on the server.  This folder is synced to Github.  At this point, further editorial work is done outside of DocTracker to these XML files (they get converted to UTF-8, annotations are added via Mashbill, etc?).  Simultaneous to this, there are further editorial processes (double proofing, etc?) that need to happen.  Currently, these processes are being done in DocTracker, but I'm having trouble conceiving how these changes are merged with the other changes that have happened outside DocTracker.

It seems that once the XML is committed to Github we would need to 'check out' the files from Github and recommit them, and then once they are recommitted re-import them into Omeka to reflect the changes these further editorial processes have wrought.

Does this seem right to everyone?  Anyone have suggestions on the best way to resolve this?

My impulse is to cut DocTracker out of the process once the XML is stored in Github because it doesn't play with Github, but I'm not sure what to replace it with.  Oxygen?

**Comment by saracarl** [comment]
I think this is resolved with the workflow we sketched out.
