### ISSUE TITLE
show "complete" status on document view

### ISSUE THREAD

**Issue by saracarl** [CivilWarGovernorsOfKentucky/Mashbill#41]
@benwbrum says he should be able to handle "mark complete" twice as a way to re-push a document to github.  Need to think through how we show "document complete" (remove from dashboard??) and how we allow completion to be re-marked.

**Comment by saracarl** [comment]
Thinking we could change the button to "mark incomplete" if it's already complete?  Then you just mark it incomplete and then complete to force a new push to github?  

Need to discuss.

**Comment by benwbrum** [comment]
Since we don't hide the 'mark complete' button on completed documents, you
can always push the button to update the XML and Github.

**Comment by saracarl** [comment]
"Mark Document Complete" if never pushed; "Update Document" if already marked complete.

**Comment by saracarl** [comment]
Add deed for marking complete.
