### ISSUE TITLE
Entity ref_id conflicts

### ISSUE THREAD

**Issue by benwbrum** [CivilWarGovernorsOfKentucky/Mashbill#42]
KHS has provided us with a set of entities that have ref_ids like `P001012` or `N001004`.  When Mashbill users create new entities, we have the ability to auto-create these ref_ids.  But what do we do about conflicting IDs?  One option is to modify the format slightly (say `PX001004` instead of `P001004`).  Another option is to define ranges, so that auto-generated ref_ids are greater than 1,000,000, while ref_ids below that number are reserved for manual entry.

**Comment by saracarl** [comment]
All the predefined ones only have 4 digit unique digits.  If we start at 10000 we should be OK.
