### ISSUE TITLE
Document Attestation in Relationships

### ISSUE THREAD

**Issue by APCurtisMA** [CivilWarGovernorsOfKentucky/Mashbill#68]
While working on "creating relationships" today in Mashbill, I noticed an issue. I am in a run of documents (about 9 or 10 documents), all with a cast of repetitive entities. When I moved from the first document in that run to the second document to create relationships, the relationships from the prior document automatically populated and assigned all the same types of relationships from the previous document. While this will be true in some instances, it is not true of all instances and Mashbill cannot determine relationship types without us assigning the relationships. For example, George Hallet, who becomes a colonel of the Enrolled Militia of Kentucky, does not have a military relationship with Gov.  Bramlette at the beginning of the document run, but once he is appointed colonel he does have a military relationship. So, automatically populating documents with relationships and relationship types proves problematic. This is especially true when we begin layering the relationships, and as those relationships continue to build,  two entities with the same relationship type have stronger connections--and the line darkens or however we chose to visualize an increase in the strength of a type of relationship.

**Comment by saracarl** [comment]
We should definitely discuss.  Entities have relationships, independent of documents.  We are just using documents to get to them.   

This is an interesting point:

 two entities with the same relationship type have stronger connections--and the line darkens or however we chose to visualize an increase in the strength of a type of relationship.

You are basically saying "a relationship with a lot of documentary evidence should be darker than one with less".  Totally not how we are doing this -- a relationship is a relationship is a relationship, no matter how much evidence there is.  (However 2 entities can have multiple *types* of relationships.)
