### ISSUE TITLE
"Document Needs Review" Button -- Broken Loop

### ISSUE THREAD

**Issue by APCurtisMA** [CivilWarGovernorsOfKentucky/Mashbill#77]
The "Document Needs Review" Button currently has a broken loop back to the Dashboard. We are currently receiving an error message, however, it does mark the document correctly for review.

**Comment by saracarl** [comment]
@APCurtisMA where should you be taken after you mark a document for review?  To me, it's "done", so the dashboard may be the most logical place.  Should you stay on the same page?

**Comment by APCurtisMA** [comment]
We talked this over and the next step would be to create relationships for that document, so it should return to that same page to allow for the user to click the create relationships function.
