### ISSUE TITLE
Review Bio Page for Omeka I-frame

### ISSUE THREAD

**Issue by saracarl** [CivilWarGovernorsOfKentucky/Mashbill#82]
Here's an example (once I get it deployed -- will update):

http://test.mashbill.discovery.civilwargovernors.org/entities/show_bio/2605
(you can try others with different entity IDs -- look in the URL when you are editing them to get an ID to replace 2605 with)

Open questions:

fields -- remove any?

Do we want "mentioned in documents" here?  If we do we'll want to link to the Omeka link for the document.

Styling -- ??.  I stripped all styling out to start with.  I'm not sure what we'll want to do with that.

**Comment by saracarl** [comment]
![screenshot from 2017-04-05 09 42 36](https://cloud.githubusercontent.com/assets/708566/24710992/5488ac9e-19e4-11e7-8616-e159b7c590e5.png)

**Comment by PatrickALewis** [comment]
Maybe bring the biography above the bibliography? Move the reference ID # up under Entity Type?

We talked about putting metadata in a separate I-frame where the current document metadata lives to give a sense of continuity with the documents. Maybe figuring out how to modify the tab features which are currently Metadata | Citation | Download to include a Mentioned in Documents tab or modifying one of the existing tabs.

**Comment by saracarl** [comment]
OK.  Will look into these.  

This is deployed on the test site now as well.
