### ISSUE TITLE
Review button after a document has been reviewed

### ISSUE THREAD

**Issue by saracarl** [CivilWarGovernorsOfKentucky/Mashbill#83]
You can mark a document "Needs Review" using a button that says "Needs Review".  When you do so, the button name changes to "Reviewed".  After the "Reviewed" button is clicked the document is marked as reviewed in the database, but the button shows "Needs Review" again.  

It seems possible a document could need multiple reviews, but I'm wondering if this is confusing?  Should we remove the button after it's been reviewed?  We could change the text, but any of my ideas seem awkward -- e.g. "Needs Review Again".

Thoughts?

**Comment by PatrickALewis** [comment]
I'm with you on the idea for a Needs Review Again button there. Flag for Additional Review? That's long. Needs More Review? Flag: More Review?
